# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rm87273-ECOMMERCE-STG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4b58e2dfc12b464e8fdae039b4510424 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1f687dd48fe9487d92ed47b92ef24cac }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4b58e2dfc12b464e8fdae039b4510424 }}/checkpoint2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rm87273-ECOMMERCE-STG'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2a8993bd04d343cd8411d6afceb9be4c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4b58e2dfc12b464e8fdae039b4510424 }}/checkpoint2:${{ github.sha }}'